### ISSUE TITLE
Colourblind mode doesn't work well with html

### ISSUE THREAD

**Issue by OmgImAlexis** [fregante/code-tag#8]
This can likely be closed but wanted to document it for others and Github support(I have a ticket open with Github). If you're using "Dark Protanopia & Deuteranopia" or "Dark Tritanopia" the syntax highlighting is using so similar colors that it basically becomes pointless.

This is a Github issue not an issue with this library.

## Dark Protanopia & Deuteranopia
![image](https://user-images.githubusercontent.com/6525926/181381297-65bc9d3e-2be8-4839-95a1-b95f4db8a747.png)

## Dark Tritanopia
![image](https://user-images.githubusercontent.com/6525926/181381509-7f72d4dc-0e15-4d8f-8bc2-508be2d86d88.png)

## Dark default
![image](https://user-images.githubusercontent.com/6525926/181381598-3524dffc-981e-4ee5-93c5-e303025f5d85.png)

**Comment by OmgImAlexis** [comment]
Tracking in https://support.github.com/ticket/personal/0/1721849

**Comment by fregante** [comment]
Sure, thanks for opening an issue
